version: '3.4'

services:
  service:
    image: galleryofluna-vk
    depends_on: 
      - derpibooru
    build:
      context: ./src/GalleryOfLuna.Vk
      dockerfile: Dockerfile
    env_file: 
      - .env
    environment:
      - Derpibooru__ConnectionString=Server=derpibooru;Database=derpibooru;User Id=postgres;Password=${POSTGRES_PASSWORD};

  derpibooru:
    image: pg-derpibooru-dump
    build:
      context: ./tools/pg-derpibooru-dump
      dockerfile: Dockerfile
    env_file: 
      - .env