version: '3.9'

services:
  service:
    image: galleryofluna-vk
    depends_on: 
      - database
    build:
      context: ./
      dockerfile: ./src/GalleryOfLuna.Vk/Dockerfile
    volumes:
      - type: bind
        source: /opt/galleryofluna/vk/appsettings.json
        target: /app/appsettings.Production.json
        read_only: true
      - type: bind
        source: /opt/galleryofluna/vk/GalleryOfLuna.Publishing.db
        target: /app/GalleryOfLuna.Publishing.db
    env_file: 
      - .env
    environment:
      - Derpibooru__ConnectionString=Server=database;Database=derpibooru;User Id=postgres;Password=${POSTGRES_PASSWORD};
      - Database__ConnectionString=Data Source=GalleryOfLuna.Publishing.db;

  database:
    image: pg-derpibooru-dump
    build:
      context: ./tools/pg-derpibooru-dump
      dockerfile: Dockerfile
    volumes:
      - pg-data:/var/lib/postgresql/data
    env_file: 
      - .env

volumes:
  pg-data: